### ISSUE TITLE
Missing version - pluto-no-op 2.0.0

### ISSUE THREAD

**Issue by Woren** [mocklets/pluto#115]
If I'm looking correctly, there is no 2.0.0 no-op version released on maven central. The latest is 1.1.3-alpha
https://search.maven.org/search?q=g:com.plutolib%20AND%20a:pluto-no-op

Also no-op version is not mentioned in readme and only debugImplementation dependency is mentioned.

Please align no-op version with newest release and add info to readme like

    debugImplementation "com.plutolib:pluto:${rootProject.ext.plutoVersion}"
    rcImplementation "com.plutolib:pluto-no-op:${rootProject.ext.plutoVersion}"
    releaseImplementation "com.plutolib:pluto-no-op:${rootProject.ext.plutoVersion}"

This is also **valid for all current plugins** which is missing no-op version completely. I didn't duplicate this issue for each plugin.

Thank you

**Comment by srtvprateek** [comment]
hey @Woren,
added support for `no-op` in all the plugins too.
