### ISSUE TITLE
Is ANR detection in the scope of pluto v2.0?

### ISSUE THREAD

**Issue by ishaan1995** [mocklets/pluto#136]
**Is your feature request related to a problem? Please describe.**
Just saw that ANR detection was already part of pluto v1. Not able to find same in the new version 2.0.
If it's not part of the scope, was there any issue with the previous implementation?

**Describe the solution you'd like**
Bring back the ANR detection as part of your latest release.

**Describe alternatives you've considered**
Considering using pluto v1 for now to detect ANRs.

**Additional context**
None

**Comment by srtvprateek** [comment]
hey @ishaan1995,
yes, we saw some instances where we were getting false positives for ANRs, causing confusion. We are working on a couple of approaches
1. make a separate ANR detection plugin
2. using bugsnag library to detect ANR for better precision.

Will keep posted on update.

**Comment by ishaan1995** [comment]
@srtvprateek What about using this library: https://github.com/SalomonBrys/ANR-WatchDog?

**Comment by srtvprateek** [comment]
ANRWatchDogs are the inferential ways to detect potential ANRs, not the actual ANR.
We are trying to figure out a better way to catch the ANRs with better accuracy.

But, since you are already using it, we'll expedite it and publish the plugin soon.
