### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by dharamveer-appyhigh** [mocklets/pluto#164]
**Describe the bug**
Exception is occurred when trying to implement any Pluto version 
for `v1.1.1` - it was duplication classes issue.
now `AAPT: error: resource android:attr/lStar not found.`

**To Reproduce**
- Add libray to `build.gradle`
- Configure the library as intended
- Build application
- Build failed with error

**Screenshots**
version `1.1.1` - 
<img width="978" alt="image" src="https://user-images.githubusercontent.com/103641331/181821900-72d99b05-c943-46af-8919-ff1e8f6274c2.png">

version `2.0.3` -
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/103641331/181815244-ca1830f1-12f8-4b1b-a670-d31528ce1b2e.png">
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/103641331/181815287-a939a925-854b-4efe-bde1-0c5b1fdb69d0.png">

**Smartphone (please complete the following information):**
 - OS: Android
 - Library Version `2.0.3` as well as `1.1.1`

**Comment by srtvprateek** [comment]
@dharamveer-appyhigh issue seems to be with `androidx.core:core-ktx` library,
can you share what version of the above library are you using? (Pluto uses version `1.7.0`)

you can also try this out https://programmerah.com/solved-aapt-error-resource-androidattr-lstar-not-found-47339/

**Comment by dharamveer-appyhigh** [comment]
@srtvprateek 
I am working on a multi-module app, so `androidx.core:core-ktx` versions are different in different modules.
Like below - 
Module 1 - `androidx.core:core-ktx:1.3.2`
Module 2 - `androidx.core:core-ktx:1.3.2`
Module 3 - `androidx.core:core-ktx:1.3.2`
Module 4 - `androidx.core:core-ktx:1.5.0`
**Main App** - `androidx.core:core-ktx:1.6.0`

And in **Main App build.gradle**, 
```
configurations.all {
            resolutionStrategy {
                force "androidx.core:core-ktx:1.6.0"
            }
 }
```

Do I have to make some changes? 
Like I have tried with `androidx.core:core-ktx:1.7.0` in **Main App build.gradle** then also same exception was thrown.

**Comment by dharamveer-appyhigh** [comment]
> @dharamveer-appyhigh issue seems to be with `androidx.core:core-ktx` library, can you share what version of the above library are you using? (Pluto uses version `1.7.0`)
> 
> you can also try this out https://programmerah.com/solved-aapt-error-resource-androidattr-lstar-not-found-47339/

@srtvprateek 
I am working on a multi-module app, so `androidx.core:core-ktx` versions are different in different modules.
Like below - 
Module 1 - `androidx.core:core-ktx:1.3.2`
Module 2 - `androidx.core:core-ktx:1.3.2`
Module 3 - `androidx.core:core-ktx:1.3.2`
Module 4 - `androidx.core:core-ktx:1.5.0`
**Main App** - `androidx.core:core-ktx:1.6.0`

And in **Main App build.gradle**, 
```
configurations.all {
            resolutionStrategy {
                force "androidx.core:core-ktx:1.6.0"
            }
 }
```

Do I have to make some changes? 
Like I have tried with `androidx.core:core-ktx:1.7.0` in **Main App build.gradle** then also same exception was thrown.

**Comment by srtvprateek** [comment]
@dharamveer-appyhigh since you are forcing version `1.6.0` for `androidx.core:core-ktx`,
Pluto is not able to find the attr added in version `1.7.0`, so it's crashing.
Can the force resolution be removed? This'll allow Pluto to keep using version `1.7.0` and crash will be avoided.

**Comment by dharamveer-appyhigh** [comment]
@srtvprateek sure, will try doing this way 👍

**Comment by dharamveer-appyhigh** [comment]
> @dharamveer-appyhigh since you are forcing version `1.6.0` for `androidx.core:core-ktx`,
> Pluto is not able to find the attr added in version `1.7.0`, so it's crashing.
> Can the force resolution be removed? This'll allow Pluto to keep using version `1.7.0` and crash will be avoided.

@srtvprateek sure, will try doing this way 👍

**Comment by jaykasliwal** [comment]
@srtvprateek Im also facing the same issue.
1) My CompileSDK version is 30 and Im using core-ktx as 1.6.0
Still getting the same issue.
2) Have even tried upgrading the core-ktx version to 1.7.0 and compilesdk version to 31 
But still facing the same issue.

Can you pls help me to resolve the same as soon as possible?

Thanks in advance.

**Comment by srtvprateek** [comment]
@jaykasliwal please check if your app module is forcing version `1.6.0`
ref https://github.com/plutolib/pluto/issues/164#issuecomment-1202027791

**Comment by srtvprateek** [comment]
@dharamveer-appyhigh @jaykasliwal we have downgraded our `android-core` version to `1.6.0` in our latest release.
Try it out once, and see if the issue is fixed.
