### ISSUE TITLE
Need a cleaner way to integrate all default modules

### ISSUE THREAD

**Issue by ishaangarg** [mocklets/pluto#167]
The new way of declaring separate dependencies for each module is great for extensibility. But leads to a very poorly readable Build.Gradle file, see how my project now has 20 dependencies for Pluto:
![image](https://user-images.githubusercontent.com/10320019/182580710-13f34300-4457-456e-89bb-b05b77ecfe19.png)

Is there a cleaner way of declaring all essential modules, especially for projects with not just 2 but 3 or more build variants?
Or maybe have a dependency that has all modules bundled?

PS: Love Pluto!

**Comment by srtvprateek** [comment]
nice suggestion @ishaangarg, let me see what we can do.

**Comment by srtvprateek** [comment]
@ishaangarg this is done,
we have published `bundle-core` with all the core plugins integrated within.

```groovy
dependencies {
  ....
  debugImplementation 'com.plutolib.plugins:bundle-core:2.0.4'
  releaseImplementation 'com.plutolib.plugins:bundle-core-no-op:2.0.4'
  ....
}
```

for more info, refer project README.md

**Comment by ishaangarg** [comment]
Awesome, thanks! 😍
