### ISSUE TITLE
URL item is not fully displayed

### ISSUE THREAD

**Issue by ReggieLei** [mocklets/pluto#173]
version 2.0.3 
<img width="218" alt="1660184399711" src="https://user-images.githubusercontent.com/11516346/184054461-c1110170-f96b-4c7e-80e9-791d88d81cb0.png">

version 2.0.4
![1660184273621](https://user-images.githubusercontent.com/11516346/184054509-39ea6bf0-3614-45fc-9a1e-c9843ab5a633.jpg)

version 2.0.3  tabLayout + viewpager2 .    It can be used in version 2.0.4 ？

**Comment by srtvprateek** [comment]
fixed in version `2.0.5`
