### ISSUE TITLE
v2.0.4 moshi & SharedPrefs crash

### ISSUE THREAD

**Issue by ishaangarg** [mocklets/pluto#176]
**Describe the bug**
ExceptionInInitializerError: Cannot serialize Kotlin type com.pluto.plugins.preferences.ui.SharedPrefFile. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
    for class com.pluto.plugins.preferences.ui.SharedPrefFile

**To Reproduce**
1. Upgrade to v2.0.4
2. run app

**Trace**
[pluto-trace.txt](https://github.com/plutolib/pluto/files/9319124/pluto-trace.txt)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a Emulator
 - OS: Android 12
 - Library Version: v2.0.4

**Comment by srtvprateek** [comment]
fixed in version `2.0.5`
