### ISSUE TITLE
Unable to integrate Pluto (Build Issue: Moshi Error)

### ISSUE THREAD

**Issue by ritesh-karmare** [mocklets/pluto#182]
@srtvprateek 

I am integrating Pluto library in my project with Crashes and Exceptions plugins.
When I try to build the project it gives following error:
`Record requires ASM8`

**Android Studio Version:** Android Studio Dolphin | 2021.3.1
**minSdkVersion:** 21
**targetSdkVersion:** 30 

**build tool:** classpath 'com.android.tools.build:gradle:7.0.3
**kotlin plugin:** org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.20

**Pluto Dependency:**
debugImplementation 'com.plutolib:pluto:2.0.5'
releaseImplementation 'com.plutolib:pluto-no-op:2.0.5'
debugImplementation 'com.plutolib.plugins:exceptions:2.0.5'
releaseImplementation 'com.plutolib.plugins:exceptions-no-op:2.0.5'

**Other Dependencies include:** Hilt, Gson, Retrofit, OkHttp

**gradle.properties**
android.enableJetifier=true
android.useAndroidX=true
android.jetifier.ignorelist=moshi-1.13.0

**Stacktrace:**

`FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeExtDexDevelopmentDebug'.
> Could not resolve all files for configuration ':app:DevelopmentDebugRuntimeClasspath'.
   > Failed to transform exceptions-2.0.5.aar (com.plutolib.plugins:exceptions:2.0.5) to match attributes {artifactType=android-dex, asm-transformed-variant=DevelopmentDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':app:DevelopmentDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=DevelopmentDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /Users/ritesh/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform library-3.5.2.aar (com.github.chuckerteam.chucker:library:3.5.2) to match attributes {artifactType=android-dex, asm-transformed-variant=DevelopmentDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not resolve all files for configuration ':app:DevelopmentDebugRuntimeClasspath'.
         > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=DevelopmentDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
            > Execution failed for AsmClassesTransform: /Users/ritesh/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
               > Record requires ASM8
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-dex, asm-transformed-variant=DevelopmentDebug, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for AsmClassesTransform: /Users/ritesh/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Record requires ASM8

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:dexBuilderDevelopmentDebug'.
> Could not resolve all files for configuration ':app:DevelopmentDebugRuntimeClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-asm-instrumented-jars, asm-transformed-variant=DevelopmentDebug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for AsmClassesTransform: /Users/ritesh/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Record requires ASM8
`

**Comment by riteshkarmare** [comment]
@srtvprateek Any update?

**Comment by srtvprateek** [comment]
@ritesh-karmare still looking into this,
not able to reproduce it

Can you try using Moshi without Pluto?

**Comment by akshaytandroid** [comment]
Same issue for me when I tried implementing the library.

**Comment by akshaytandroid** [comment]
adding` android.jetifier.blacklist = com.squareup.moshi` to the gradle.properties helped me get rid of this error.
