### ISSUE TITLE
Build issues because of duplicate attribute corner_radius

### ISSUE THREAD

**Issue by amankgo** [mocklets/pluto#19]
**Describe the bug**
Build issues because of duplicate attribute. 
`AAPT: error: duplicate value for resource 'attr/corner_radius' with config ''`

https://github.com/mocklets/pluto/blob/445ad948e282a2054044056bf9a26c15b0820b82/pluto/src/main/res/values/attr.xml#L5

Can we append resource prefix here also to not use a common name which might conflict with some other library in big projects?

**To Reproduce**
1. Add `implementation 'com.crystal:crystalrangeseekbar:1.1.3'` library (Just to replicate the conflict)
2. Build.

**Expected behavior**
There should be no AAPT error and project should build without any issue.

**Build Environment:**
 - Library Version : All versions

**Comment by srtvprateek** [comment]
fixed, PR: https://github.com/mocklets/pluto/pull/22

**Comment by amankgo** [comment]
Thank you for quick fix. Can you tell when are you planning for next release.
Also I am happy to contribute to this project if you like.

**Comment by srtvprateek** [comment]
working on 1 issue currently, will be releasing new version soon.

**Comment by srtvprateek** [comment]
i would love to see you contributing 💯 
currently, our contribution guidelines are WIP, will publish those soon.

**Comment by srtvprateek** [comment]
library version `v1.0.4` is live with the fix

**Comment by saranakkaraviwat** [comment]
@srtvprateek i found this issue again in 2.0.1-beta

**Comment by srtvprateek** [comment]
@saranakkaraviwat thanks for raising this,
this is fixed in https://github.com/plutolib/pluto/pull/137, will be available in the next version.
