### ISSUE TITLE
use AppStartup library instead of no-op

### ISSUE THREAD

**Issue by prudhvir3ddy** [mocklets/pluto#20]
**Is your feature request related to a problem? Please describe.**
currently, we have to add two dependencies, one for debug and one for release. 

**Describe the solution you'd like**
AppStartup library instead initialises the library using ContentProvider. 
https://developer.android.com/topic/libraries/app-startup

**Describe alternatives you've considered**

**Additional context**

**Comment by srtvprateek** [comment]
thanks @prudhvir3ddy, 
will explore this 👍🏽

**Comment by prudhvir3ddy** [comment]
@srtvprateek while this is possible for the initialisation of library i can see for adding interceptor people again have to check if (BuildConfig.Debug) which we don't want.. 

closing this, one day we might find a solution for this but currently doesn't look like it's possible. Thanks
