### ISSUE TITLE
Unresolved reference error while generating Release universal apk

### ISSUE THREAD

**Issue by nikhil-chavanke** [mocklets/pluto#201]
**Describe the bug**
We are getting the following error when executing task `:app:compileReleaseKotlin` while building the release universal apk

`e: /opt/buildagent/work/876c90ec829e601/sharechat/initializer/PlutoInitializer.kt: (81, 13): Unresolved reference: mainThreadResponseThreshold
Execution failed for task ':app:compileReleaseKotlin'. `

`org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
e: /opt/buildagent/work/876c90ec829e601/sharechat/initializer/PlutoInitializer.kt: (84, 58): Unresolved reference: threadStateMap`

**Additional context**
We are accessing `mainThreadResponseThreshold` and `threadStateMap` from our app through the below code

`PlutoExceptions.apply {`
            `mainThreadResponseThreshold = 5000L`
            
            setANRHandler { _, exception ->
                exception.printStackTrace()
                PlutoLog.e("AppNotResponding", exception.threadStateMap)
            }
`}
`

dependencies declared :

`pluto-library = "com.plutolib:pluto:2.0.8"`
`pluto-noOp = "com.plutolib:pluto-no-op:2.0.8"`

`pluto-pluginLibrary = "com.plutolib.plugins:bundle-core:2.0.8"`
`pluto-pluginNoOp = "com.plutolib.plugins:bundle-core-no-op:2.0.8"`

**Comment by nikhil-chavanke** [comment]
@srtvprateek any idea about this issue?

**Comment by srtvprateek** [comment]
upgrade to ver `2.0.9`
