### ISSUE TITLE
Easy access button is not working properly

### ISSUE THREAD

**Issue by sonusourav** [mocklets/pluto#24]
**Describe the bug**
Many times even when I click on the Pluto easy access button (floating on top of my app), it does not open the Pluto screen
Sometime, it get opened, but most of the time it does not open.

**Screenshots**

https://user-images.githubusercontent.com/34706326/130896315-f8531a15-0221-4f14-9e7f-21e125c48e79.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung F41
 - OS: Android 11
 - Library Version 1.0.0

**Comment by srtvprateek** [comment]
@sonusourav can you attach any video for the issue

**Comment by sonusourav** [comment]
@srtvprateek Have attached the video for the issue (although the press action might not be very much visible in the video)

**Comment by mimoccc** [comment]
Debug logcat info could be usefull. 
(minimally if activity is started after click on button)
Possible scenario is that Intent need to have flag reorder to front, a may be log is open under application, or your application is also in alert window mode.

**Comment by srtvprateek** [comment]
@sonusourav made some improvement fixes around `Easy access button` 
can you try this once on version 1.0.7

**Comment by sonusourav** [comment]
Hey looks like you have forced the minSDk to be 21. We have 19 as minSDK so won't be able to use this lib in that case. But we are planning to upgrade in the future. Just wanted to know, any strong reason to use 21 instead of 19

**Comment by sonusourav** [comment]
Btw, now some weird issue is coming. I could see multiple copies of button and those persists even after app exit.
Attached screenshots:

![2021_09_02_08_47_42](https://user-images.githubusercontent.com/34706326/131871179-77631ab3-36e6-410e-9748-7813b68ce7e9.jpeg)

![2021_09_02_08_48_16](https://user-images.githubusercontent.com/34706326/131871203-58a55793-3596-4725-801c-3ff0e014bc66.jpeg)

**Comment by srtvprateek** [comment]
> Hey looks like you have forced the minSDk to be 21. We have 19 as minSDK so won't be able to use this lib in that case. But we are planning to upgrade in the future. Just wanted to know, any strong reason to use 21 instead of 19

initially we were supporting `minSdk=16`, then we decided to upgraded to inorder to get rid of `compat` code, let me see if we can downgrade to `19` to keep supporting you.

for the multiple `Easy Access button` issue, can you share
- Device model
- Android OS version

**Comment by sonusourav** [comment]
Device model and Android OS version are same as mentioned in the issue description

**Comment by neeshurajput** [comment]
@srtvprateek The issue can be reproduced as follows :
Open the app
Press back button and move out of the app
Open the app again
