### ISSUE TITLE
Open pluto in seperate window

### ISSUE THREAD

**Issue by stefanusayudha** [mocklets/pluto#257]
**Is your feature request related to a problem? Please describe.**
i wonder if we can open pluto in seperate window. I can't find any instruction to do so, so i assume there are none or not yet able to do so.

**Describe the solution you'd like**
We can start pluto activity as new window instead of push to current activity stack.
We can do that by adding FLAG_ACTIVITY_MULTIPLE_TASK to the intent.
I'd like to help with this enhancement if it not yet available.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by srtvprateek** [comment]
enabled in https://github.com/androidPluto/pluto/commit/b4dfd8d5a105946353d353381385103f698c61cd
