### ISSUE TITLE
Request Body Shows Wrong Value (Long type)

### ISSUE THREAD

**Issue by kristokhosim** [mocklets/pluto#265]
**Describe the bug**
There's an issue on request body json
I have payload with **long** type, but in request body it's not show as Long type

Take a look on this image 
![image](https://github.com/androidPluto/pluto/assets/35672774/c76a0e00-c6e2-44d8-b7e4-8cb356d023f8)
![image](https://github.com/androidPluto/pluto/assets/35672774/2181f887-b035-4536-8155-ee1ca07bb823)

**Expected behavior**
Should show as Long type

**Comment by srtvprateek** [comment]
@kristokhosim what version are you using?
this issue should be fixed with https://github.com/androidPluto/pluto/pull/237, please update to latest version & check once

**Comment by kristokhosim** [comment]
Oh yes, sorry I am using v2.1.3
Now fixed on v2.1.6

Thank you @srtvprateek

**Comment by srtvprateek** [comment]
great!!
it ll also resolve the issue where int value is being shown as float, like `odometer`
