### ISSUE TITLE
Content-Type header is null

### ISSUE THREAD

**Issue by Woren** [mocklets/pluto#279]
Pluto version 2.1.7 with network plugin. Previous version 2.1.3 was working correctly. PlutoInterceptor was deleted in favor of "addPlutoKtorInterceptor".

Based on this RFC content-type can be null in headers
https://www.rfc-editor.org/rfc/rfc9110.html#name-content-type

For example this should be valid headers (no content-type is set)
`Headers [access-control-allow-credentials=[true], access-control-allow-origin=[https://www.xyz.cz], alt-svc=[h3=":443"; ma=86400], cache-control=[no-cache], cf-cache-status=[MISS], cf-ray=[8092ba23G], content-length=[0], content-security-policy=[frame-ancestors 'self';], date=[Tue, 19 Sep 2023 15:05:29 GMT], location=[https://www.xyz.cz/api/catalog/v1/1?ui=HCAEJQ&pgri=mAAI], nonstatic=[0], permissions-policy=[autoplay=(), camera=(), microphone=(), geolocation=(self)], pragma=[no-cache], referrer-policy=[strict-origin-when-cross-origin], server=[cloudflare], set-cookie=[lb_id=dc8f3fc6ed33228272; expires=Tue, 19-Sep-23 17:05:28 GMT; max-age=7200; httponly; path=/], strict-transport-security=[max-age=31536000; includeSubDomains; preload], vary=[Accept-Encoding], x-content-type-options=[nosniff], x-frame-options=[SAMEORIGIN], x-proxy-cache=[MISS], App-Log-Tag=[487271637]]`

The problem is with lines of code in KtorResponseConverter around line 35 with "fun HttpResponse.extractBody()" where there is contentType().toString() which will generate "null" String for contentType() null. Then this "null" String is handed to Ktor which will throw exception as shown below. This will cause in Pluto Network UI "indefinite progress" and no data is sent to the application. 

Same is probably true also for OkHttp interceptor.

Hopefully this will be easy fix. Thank you.

```
io.ktor.http.BadContentTypeFormatException: Bad Content-Type format: null
at io.ktor.http.ContentType$Companion.parse(ContentTypes.kt:123)
at com.pluto.plugins.network.intercept.NetworkData$Body.<init>(NetworkData.kt:41)
at com.pluto.plugins.network.ktor.internal.KtorResponseConverter.extractBody(KtorResponseConverter.kt:35)
at com.pluto.plugins.network.ktor.internal.KtorResponseConverter.convert(KtorResponseConverter.kt:14)
at com.pluto.plugins.network.ktor.PlutoKtorHelperKt$addPlutoKtorInterceptor$1.invokeSuspend(PlutoKtorHelper.kt:24)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                           
```

**Comment by srtvprateek** [comment]
hey @Woren ,
seems like there is some confusion here.
PlutoInterceptor is replaced with `addPlutoOkhttpInterceptor()`, not `addPlutoKtorInterceptor()`.

Please read migration doc: https://github.com/androidPluto/pluto/wiki/Migrating-Network-plugin-to-version-2.1.7.

Let me know if the issue persist even after the change.

`addPlutoKtorInterceptor()` is created to support debugging of Ktor based network clients.

**Comment by Woren** [comment]
We're using both Ktor and OkHttp - we have no issue with this migration and network calls from both are visible in Pluto UI. The problem is incorrect handling of cases when Content-Type header is null which will cause Exception and Pluto is not working for that HTTP request/responses (see above).

**Comment by srtvprateek** [comment]
understood, will check this.

**Comment by srtvprateek** [comment]
hey @Woren,
can you also share the code snippet for how you are creating the `HttpClient`?
or refer [KtorNetwork](https://github.com/androidPluto/pluto/blob/develop/sample/src/main/java/com/sampleapp/functions/network/internal/ktor/KtorNetwork.kt) file to see what's the difference.

**Comment by Woren** [comment]
Our Ktor/OkHttp incialization is very complex - multiple files and multiple methods.

But for example this is for Ktor
`private fun HttpClient.setInterceptors(interceptors: List<KtorInterceptor>): HttpClient = this.apply {
        interceptors.forEach { plugin(HttpSend).intercept(it) }
        if (Config.IS_DEBUG) addPlutoKtorInterceptor()
    }`
  
In our case is Content-Type null for 302 requests.

I think even if "some how" our setup is incorrect there can't be mentioned above call of "contentType().toString()" which will convert empty and by RFC valid content type to "null" string value.
