### ISSUE TITLE
return type of addPlutoOkhttpInterceptor() 

### ISSUE THREAD

**Issue by SurajKGoyal** [mocklets/pluto#283]
while adding this interceptor to the OkHttpClient, It must have a return type of the same OkHttpClient.Builder, instead it's return type in Unit. Can't build the client via this.

Please let me know if I am missing something here.

**Comment by srtvprateek** [comment]
@SurajKGoyal please refer to [this](https://github.com/androidPluto/pluto/blob/develop/sample/src/main/java/com/sampleapp/functions/network/internal/okhttp/Network.kt)

`addPlutoOkhttpInterceptor()` is not a builder method, instead its a wrapper over `addInterceptor()` method.
Its just a extension method over `OkHttpClient.Builder`
