### ISSUE TITLE
Please remove internal flag com.pluto.plugins.network.okhttp.PlutoInterceptor 

### ISSUE THREAD

**Issue by mlilienberg** [mocklets/pluto#292]
In more complex apps, the okhttp client might be created in factory methods or other ways of abstraction. In our case we pass the list of interceptors we want to add to a factory method. Since one of the recent pluto updates we can not do this anymore because the class is flagged as internal.

For now we use a workaround that is not nice but working.

```
val interceptor = OkHttpClient.Builder().addPlutoOkhttpInterceptor().interceptors().first()
//Pass this interceptor to your HttpClientFactory method
```

**Comment by srtvprateek** [comment]
hey @mlilienberg,
is it possible the share the code snippet where the list of interceptor is being read & added to Okhttp Builder.
