### ISSUE TITLE
Waiting for response is endless if POST returns only error code and empty response

### ISSUE THREAD

**Issue by cj-marius-duna** [mocklets/pluto#314]
For more details please see the attachments.
The main idea if I get for response only the error code(200, 202, 4xx) back with empty response than the UI is showing "waiting for response" in endless loop
<img width="405" alt="Screenshot 2024-05-03 at 10 36 45" src="https://github.com/androidPluto/pluto/assets/81554727/c8a0cae0-2c4c-435d-8070-71607df51e7d">
<img width="1216" alt="Screenshot 2024-05-03 at 10 34 32" src="https://github.com/androidPluto/pluto/assets/81554727/97cd0304-892f-4756-a203-3c15103f09f7">

**Comment by cj-marius-duna** [comment]
While analysing the logs using Proxyman then the API call ended successfully

**Comment by Duna** [comment]
I confirm that one, the bug is there. Spinner never ends, even if the call is successful. Empty body returned from API call
