### ISSUE TITLE
Version 2.2.3 of Pluto Library Fails to Resolve

### ISSUE THREAD

**Issue by YouSsef3Ssam** [mocklets/pluto#323]
**Describe the bug**
When updating the Pluto library version from `2.2.2` to `2.2.3`, the library fails to download, resulting in the following build error: `Failed to resolve: com.plutolib:pluto:2.2.3`.

**To Reproduce**
1. Update the Pluto library version in your `build.gradle.kts` or equivalent configuration file from `2.2.2` to `2.2.3`.
2. Attempt to sync or build the project.

**Expected behavior**
The library should be successfully downloaded and integrated into the project without any errors.

**Screenshots**
<img width="704" alt="Screenshot 2024-09-01 at 5 46 48 PM" src="https://github.com/user-attachments/assets/5364698b-7828-4fdc-a4b6-981de051b007">

**Comment by srtvprateek** [comment]
there have been some issue with build pipeline for 2.2.3,
please continue using 2.2.2, ll update once the new version is live.
