### ISSUE TITLE
The call can be simplified same behavior as Timber have, no tag string is needed or can be optional

### ISSUE THREAD

**Issue by mimoccc** [mocklets/pluto#38]
**Is your feature request related to a problem? Please describe.**
Love the Timber calls that does not need a tag string, also missing calls for exceptions only.

**Describe the solution you'd like**
For exceptions:
    @JvmStatic
    fun e(tr: Throwable?) {
        e(tr?.message ?: "", tr)
    }
Where to get tags:
From stacktrace, something like:
 val tag = Thread.currentThread().stackTrace.let {
                if (it.size > 3) it[3] else null
            }.let {
                it?.className?.lastPart(".") ?: this::class.simpleName ?: ""
            }
            fun String.lastPart(s: String): String = if (this.contains(s)) this.split(s).last() else this

**Describe alternatives you've considered**

**Additional context**

**Comment by srtvprateek** [comment]
@mimoccc Pluto now allows Timber logs also. This should address your concern.
https://github.com/plutolib/pluto/tree/develop/pluto-plugins/plugins/logger#add-pluto-logs
