### ISSUE TITLE
FileProvider - conflict

### ISSUE THREAD

**Issue by Woren** [mocklets/pluto#59]
**Describe the bug**
Can't build application when using own FileProvider.

**To Reproduce**

Have your own FileProvider in your AndroidManifest.xml

>         <provider
>             android:name="androidx.core.content.FileProvider"
>             android:authorities="${applicationId}.fileProvider"
>             android:exported="false"
>             android:grantUriPermissions="true">
>             <meta-data
>                 android:name="android.support.FILE_PROVIDER_PATHS"
>                 android:resource="@xml/provider_paths" />
>         </provider>

When building application you get error message:

> C:\Android\project\src\debug\AndroidManifest.xml:14:13-64 Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(com.your.app.debug.fileProvider) from [:moduleName] AndroidManifest.xml:14:13-64
	is also present at [com.mocklets:pluto:1.0.5] AndroidManifest.xml:21:13-68 value=(pluto___com.your.app.debug.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:12:9-20:20 to override.
C:\Android\project\src\debug\AndroidManifest.xml:19:17-55 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from [:moduleName] AndroidManifest.xml:19:17-55
	is also present at [com.mocklets:pluto:1.0.5] AndroidManifest.xml:26:17-68 value=(@xml/pluto___file_provider_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

**Expected behavior**
Application can be build using own FileProvider without conflict.

**Additional context**
Gradle 7.1.1
AGP 7.0.0

**Comment by srtvprateek** [comment]
this has been fixed in **https://github.com/mocklets/pluto/pull/55**
will be live in version **1.0.6**
