### ISSUE TITLE
Local Database Viewer

### ISSUE THREAD

**Issue by jimlyas** [mocklets/pluto#65]
## Is your feature request related to a problem? Please describe.
It's not related to a problem, but i find it quite useful in the future.

## Describe the solution you'd like
So the current version have the ability to look keys and values of `SharedPreference`. And I think Local Database Inspector would be a great addition. Furthermore, the ability to update values to the database is good too.

## Describe alternatives you've considered
For alternative, i think just able to see the local database from the device would be helpful.

## Additional context
So actually i'm stumble upon this [library](https://github.com/infinum/android_dbinspector) and i think it would be really to good to combine it here.

**Comment by sonusourav** [comment]
+1 For this. This is something that I was even planning to include

**Comment by srtvprateek** [comment]
@jimlyas @sonusourav Pluto 2.0.0+ now supports Rooms DB and Datastore Preferences
