### ISSUE TITLE
Logger - share option

### ISSUE THREAD

**Issue by Woren** [mocklets/pluto#66]
**Is your feature request related to a problem? Please describe.**
I have in code for example this log:
PlutoLog.e("Flow.catchAndPrint", it.message, it)
but in Pluto Viewer there is no share option for this.
![image](https://user-images.githubusercontent.com/1436458/131849934-4e996fea-eb0e-471b-bfed-e4f4f47c4f1a.png)

For ANR and Crash there is this option.
![image](https://user-images.githubusercontent.com/1436458/131850490-6e20abfd-9f26-4f08-b06f-42919299123f.png)

**Describe the solution you'd like**
Add similar option for sharing logger info. For example only for Throwable / Stacktrace.

**Describe alternatives you've considered**
Copy the whole text with long press and using OS Copy feature.

**Comment by srtvprateek** [comment]
@Woren seems like the Logger details bottomsheet is getting scrolled to bottom in case of too much data,
can you try to scroll to top, there will be a sharing option there.

will fix it in next release.

> to test it, try adding a debug PlutoLog without exception logs.
