### ISSUE TITLE
Catch Memory Leaks

### ISSUE THREAD

**Issue by sonusourav** [mocklets/pluto#67]
**Is your feature request related to a problem? Please describe.**
Pluto should be able to capture memory leaks also, thus becoming a superset of Leak Canary.

For Context: We are using leak canary but we like your library and so was thinking to use this for debugging from now on. But, we are also using Leak canary and if Pluto could include the feature provided by Leak Canary (capture memory leaks), we could simply replace it with Pluto.

In addition, as somebody has already raised an issue, if we can add database inspector also in the Pluto, that would be awesome.
Something similar to this https://github.com/amitshekhariitbhu/Android-Debug-Database

**Comment by srtvprateek** [comment]
hey @sonusourav, glad you like Pluto, to answer your queries
- we don't see how we can add more value to what LeakCanary is already providing. If we can provide better leak management, we would definitely look into it, but there is no roadmap for that yet. If you have any use-case in mind, please do share.
- we are actively looking into integrating Database Inspector, you will hear soon from us on this.

**Comment by srtvprateek** [comment]
@sonusourav Pluto now supports Rooms DB on version `2.0.0+`
