### ISSUE TITLE
read timeout on release build

### ISSUE THREAD

**Issue by Shubhamsdr3** [mocklets/pluto#77]
**Describe the bug**
I am getting read timeout while building the release apk. My concern is, why it's resolving no-op dependency on release build ?

**Version**

    debugImplementation 'com.mocklets:pluto:1.0.2-beta'
    releaseImplementation'com.mocklets:pluto-no-op:1.0.2-beta'

**Screenshots**

<img width="790" alt="Screen Shot 2021-09-16 at 4 27 01 PM" src="https://user-images.githubusercontent.com/17290386/133601630-53976760-570f-48ea-9973-1a39309f599b.png">

**Comment by srtvprateek** [comment]
@Shubhamsdr3 since jcenter is shutting down, we have migrated to mavenCentral, 
please refer to the [latest docs](https://github.com/mocklets/pluto#integrate-pluto-in-your-application)

**Comment by Shubhamsdr3** [comment]
Thank you @srtvprateek :)
