### ISSUE TITLE
Response Body shows - " ~ Binary Data " in Pluto

### ISSUE THREAD

**Issue by poojasngh432** [mocklets/pluto#81]
**No Response Body info in pluto for some apis while it works for apis we're calling through Retrofit**

**To Reproduce**

the code for making the call is this(I have added PlutoInterceptor in the okhttp client's code):
  ```
public static String makeRequest(Request request) throws IOException, HttpException, JSONException, NoNetworkException
    {
        if (NetworkUtils.isNetworkAvailable(BaseApp.getContext()))
        {
            return doRequest(request);
        } else
        {
            throw new NoNetworkException(BaseApp.getContext().getResources().getString(R.string.no_network_message));
        }
    }

    private static String doRequest(Request request) throws IOException, HttpException, JSONException
    {
        OkHttpClient httpClient = Factory.getOkHTTPClient();
        Response response = httpClient.newCall(request).execute();
        String body = response.body().string();
    }
```

**Expected behavior**
![Screenshot_2021-09-20-17-32-51-216_com aranoah healthkart plus](https://user-images.githubusercontent.com/29397540/133999984-7e3366b0-28c9-4de8-a19c-b4060e54b21e.jpg)

**Screenshots**
![Screenshot_2021-09-20-17-32-40-945_com aranoah healthkart plus](https://user-images.githubusercontent.com/29397540/133999962-5a66ac72-ffbb-4447-a6f4-75e91ac9e28b.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi
 - Library Version 1.0.1

**Additional context**
It shows the response data for call made through Retrofit
```
fun getRetrofitInstance(type: Type, typeAdapter: Any): Retrofit {

            return Retrofit.Builder()
                    .baseUrl(HkpApi.RETROFIT_SERVER_BASE_URL)
                    .addCallAdapterFactory(RxErrorHandlingCallAdapterFactory.create())
                    .addConverterFactory(gsonConverterForCustomDeserializer(type, typeAdapter)!!)
                    .client(getOkHTTPClient(true))
                    .build()
}
```

**Comment by srtvprateek** [comment]
hi @poojasngh432, can you share the content-type value for the API.
you can refer to the Request header section.

**Comment by poojasngh432** [comment]
Hi @srtvprateek 
content-type is 
application/*json - (When Response data is not showing)
application/json - (When Response data is showing)

**Comment by srtvprateek** [comment]
@poojasngh432 not sure how to simulate `application/*json` content type,
can you point me to some documentation for it.

**Comment by poojasngh432** [comment]
The value passed for Content-type is "application/json "(Confirmed this by debugging).
But in the cases when response data is not showing, content-type is "application/*json" in pluto header data for response

Attaching full ss of both cases with Header data -

![Screenshot_2021-09-20-17-32-40-945_com aranoah healthkart plus (1)](https://user-images.githubusercontent.com/29397540/134115544-745e4658-af73-4228-b465-85c8b968da0a.jpg)

![Screenshot_2021-09-20-17-32-51-216_com aranoah healthkart plus (1)](https://user-images.githubusercontent.com/29397540/134115555-a2b23f73-5029-4636-9538-8ad5e7916731.jpg)
