### ISSUE TITLE
Pluto widget like option

### ISSUE THREAD

**Issue by Yaroslav-Syrota-Tictrac** [mocklets/pluto#96]
We use your library to monitor the status of requests and responses in our application. But we faced one problem - Pluto's widget leads to conflicts with automation tests of the application on the BrowserStack. It would be nice to add an option that will programmatically disable the use of the widget and Over Other App request, depending on the needs of the developers, leaving access only through the notification panel (as is done in some libraries). Perhaps by using the builder when initializing Pluto, something like -
Pluto.Builder().overOtherAppsOption(false).build().initialize(this)

Sincerely. Yaroslav.

**Describe the solution you'd like**

using the builder when initializing Pluto ->

Pluto.Builder().overOtherAppsOption(false).build().initialize(context: this)

fun overOtherAppsOption(isEnabled: Boolean = true)
{
    if (isEnabled) allowOverOtherAppOption()
}

**Comment by srtvprateek** [comment]
hey @Yaroslav-Syrota-Tictrac,
is disabling the widget option from Settings, not working for you?

**Comment by Yaroslav-Syrota-Tictrac** [comment]
@srtvprateek will check. I'll let you know. Thanks a lot for your help and improvements!!!

**Comment by srtvprateek** [comment]
@Yaroslav-Syrota-Tictrac we now support opening Pluto UI programmatically without `draw over other apps` permission.
from version `1.1.3` onwards, you can call `Pluto.showUi()` to open Pluto UI directly

**Comment by Yaroslav-Syrota-Tictrac** [comment]
@srtvprateek it's working for us, thanks a lot!!!!
