### ISSUE TITLE
Pluto should implement also openLog method

### ISSUE THREAD

**Issue by mimoccc** [mocklets/pluto#97]
Could be nice to have possibility to open PlutoActivity from hosting activity.
Something like:

Pluto.openLog(Screen.CrashAndAnr)

**Comment by srtvprateek** [comment]
@mimoccc so you need a method from which you can open the Pluto UI directly without notification/widget option?

**Comment by mimoccc** [comment]
Unsure now the right reason i wrote this to you but yes.
For example could be nice to open activity with log from intent or a floating action button instead of your notification or your chrome button.
Enough could be if you make activity public, open and exported.
Programmer can then adapt your activity and modify as wish.
Unsure why one made classes final and internal.
All success is in to publish library with open classes if they realy not need to be internal.
As library become more users then withouth forks and uncomitted private modifications.

**Comment by srtvprateek** [comment]
hey @mimoccc,
this is taken care in the [new architecture](https://github.com/mocklets/pluto/pull/109).
will have capability to open any debugger screen with `Pluto.open(DEBUGGER_ID)`

**Comment by srtvprateek** [comment]
this is live with version `2.0.0`
